name: Demo Actions
on: push 

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
           - name: Checout repo
             uses: actions/checkout@v4
           
           - name: Show welcome message
             run: echo "Hello Self taught developers"

           - name: Create new file 
             run: touch demo.html

           - name: Check if files exist
             run: mv demo.html demo.txt
