name: App
on: push 
jobs: 
  first_job:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout Repo
         uses: actions/checkout@v4

       - name: Execute Cowsat CMD
         run: sudo apt-get install cowsay -y

       - name: Show Cowsat CMD
         run: cowsay -f dragon "Run for cover, Im dragon" >> demo.txt
        
       - name: List file
         run: ls 

       - name: Find file
         run: grep -i "dragon"  dragon.txt
     
    
  
