name: Script

on: push 

jobs:
    first: 
        runs-on: ubuntu-latest
        steps:

        - name: file 
          uses: actions/checkout@v4

        - name: Execute script
          run: |
            chmod +x ganesh.sh
            ./ganesh.sh
